### ISSUE TITLE
Code not running -Tensorflow gather_nd bounds problem

### ISSUE THREAD

**Issue by MerinS** [sjvasquez/web-traffic-forecasting#1]
I was trying to get this code running on my local system --> I am facing this error- 

Traceback (most recent call last):
  File "cnn.py", line 414, in <module>
    nn.fit()
  File "/Users/srikanthjammy/Documents/midterm/tf_base_model.py", line 142, in fit
    feed_dict=val_feed_dict
  File "/Users/srikanthjammy/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/Users/srikanthjammy/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/Users/srikanthjammy/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/Users/srikanthjammy/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: flat indices[15493, :] = [121, -1] does not index into param (shape: [128,486,32]).
[[Node: GatherNd_23 = GatherNd[Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](add_24, stack_23)]]

Caused by op u'GatherNd_23', defined at:
  File "cnn.py", line 412, in <module>
    num_decode_steps=64,
  File "cnn.py", line 121, in __init__
    super(cnn, self).__init__(**kwargs)
  File "/Users/srikanthjammy/Documents/midterm/tf_base_model.py", line 99, in __init__
    self.graph = self.build_graph()
  File "/Users/srikanthjammy/Documents/midterm/tf_base_model.py", line 344, in build_graph
    self.loss = self.calculate_loss()
  File "cnn.py", line 366, in calculate_loss
    y_hat_decode = self.decode(y_hat_encode, conv_inputs, features=self.decode_features)
  File "cnn.py", line 265, in decode
    slices = tf.reshape(tf.gather_nd(conv_input, idx), (batch_size, dilation, shape(conv_input, 2)))
  File "/Users/srikanthjammy/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1338, in gather_nd
    name=name)
  File "/Users/srikanthjammy/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)

On searching online, looks like it is a tensorflow bug -- https://github.com/tensorflow/tensorflow/issues/12608
Did you face this issue?
I'm running the data on CPU btw. 
versions of numpy, pandas, scikit and tensorflow are as you had mentioned.

**Comment by MerinS** [comment]
Update -> It only happens when I'm running the code on the Kaggle input data set - 2(train_1.csv). It doesn't happen when running on Kaggle input data set - 1(train_2.csv). Any idea why?

**Comment by cylee81** [comment]
Hi @MerinS  did you solve this problem ? I think this is because of the index in GatherNd which they added in Tensorflow document recently. 

" Note that on CPU, if an out of bound index is found, an error is returned. On GPU, if an out of bound index is found, a 0 is stored in the corresponding output value."

Therefore, you should force index >= 0.

**Comment by hieuhc** [comment]
Hi @cylee81, can you elaborate more on how to force index >= 0. I ran into the same error and tried to replace negative index in the same way numpy handles negative indexes, but didn't work (loss increases after 10 epoches). This is how I handle the negative:
`
queue_begin_time = self.encode_len - dilation - 1

temporal_idx_origin = tf.expand_dims(queue_begin_time, 1) + tf.expand_dims(tf.range(dilation), 0)
            temporal_idx_origin = tf.reshape(temporal_idx_origin, [-1])
            temporal_idx_remove_neg = temporal_idx_origin + tf.shape(conv_input)[1]
            temporal_idx = tf.where(tf.greater_equal(temporal_idx_origin, tf.constant(0)),
                                    temporal_idx_origin,
                                    temporal_idx_remove_neg)
`

**Comment by sjvasquez** [comment]
I may have addressed this problem in the model located in cf/cnn.py by simply padding the inputs and shifting the indices forward.  The problem may stem from something else though.

https://github.com/sjvasquez/web-traffic-forecasting/blob/master/cf/cnn.py#L399

**Comment by GSvensk** [comment]
The problem goes away if you run the model on a GPU. I was unable to force the indicies to go >= 0 and unfortunately the problem exists for the model in cf/cnn.py as well.

Could this error be indicative of something being slightly off with the indexing?
